


// DROP TABLE `auth`;

// CREATE TABLE auth (
//     id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
//     username VARCHAR(30) NOT NULL UNIQUE,
//     email VARCHAR(30) NOT NULL,
//     token VARCHAR(30) NOT NULL,
//     password VARCHAR(150),
//     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
// )